version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  inventory-service:
    build: ./inventory_service
    container_name: inventory-service
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - inventory_data:/app
    ports:
      - "8001:8000"

  order-service:
    build: ./order_service
    container_name: order-service
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - INVENTORY_SERVICE_URL=http://inventory-service:8000
    volumes:
      - order_data:/app
    ports:
      - "8002:8000"

  notification-service:
    build: ./notifications_service
    container_name: notification-service
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MAILTRAP_USER=9314a7dd39cffd
      - MAILTRAP_PASS=2617cf4f458d96
      - TO_EMAIL=gcristianati@gmail.com
    ports:
      - "8003:8000"

volumes:
  inventory_data:
  order_data:
